---
clamav_freshclam_config: /etc/freshclam.conf
clamav_milter_config: /etc/mail/clamav-milter.conf
clamav_milter_group: clamilt
clamav_milter_socket: /var/run/clamav-milter/clamav-milter.sock
clamav_milter_user: clamilt
clamd_config: /etc/clamd.d/scan.conf
clamd_pid: /var/run/clamd.scan/clamd.pid
clamd_service: clamd@scan
clamscan_user: clamscan
clamscan_group: clamscan
clamscan_socket: /var/run/clamd.scan/clamd.sock
development_packages:
 - "@development"
 - "kernel-devel-{{ ansible_kernel }}"
dev: devel
dir_apache2_conf: /etc/httpd
dir_opendkim_keys: /etc/opendkim/keys
grp_sudo: wheel
pkg_apache2: httpd
pkg_bind_utils: bind-utils
pkg_clamd: clamd
pkg_dovecot: dovecot
pkg_dovecot_managesieved: dovecot-pigeonhole
pkg_dovecot_sieve: dovecot-pigeonhole
pkg_fail2ban: fail2ban
pkg_fail2ban_systemd: fail2ban-systemd
pkg_gstreamer: gstreamer
pkg_keepass2: keepass
pkg_latex_base: texlive-collection-latex
pkg_latex_extra: texlive-collection-latexextra
pkg_latex_recommended: texlive-collection-latexrecommended
pkg_lightning: thunderbird-lightning
pkg_lightning_gdata: thunderbird-lightning-gdata
pkg_log_monitor: logwatch
pkg_mod_php: php
pkg_mod_wsgi: mod_wsgi
pkg_mysql_server: mariadb-server
pkg_network_manager_openvpn: NetworkManager-openvpn
pkg_openssh_clients: openssh-clients
pkg_perl_dkim: perl-Mail-DKIM
pkg_php_gd: php-gd
pkg_php_mysql: php-mysqlnd
pkg_php_pdo: php-pdo
pkg_postfix_doc: postfix
pkg_pyzor: pyzor
pkg_rake: rubygem-rake
pkg_razor: perl-Razor-Agent
pkg_ruby_rails: rubygem-rails
pkg_rxvt_unicode: rxvt-unicode
pkg_saxon: saxon-scripts
pkg_spamass_milter: spamass-milter-postfix
pkg_texlive_base: texlive-collection-basic
pkg_texlive_fonts: texlive-collection-fontsrecommended
pkg_texlive_fontutils: texlive-collection-fontutils
pkg_texlive_generic: texlive-collection-genericrecommended
pkg_texlive_publishers: texlive-collection-publishers
pkg_texlive_science: texlive-collection-science
pkg_unattended_upgrades: yum-cron
pkg_vim: vim-enhanced
pkg_virtualenv: python-virtualenv
pkg_wireshark: wireshark-gnome
pkg_xorg_font_utils: xorg-x11-font-utils
pkg_xorg_input: xorg-x11-drv
pkg_xorg_server_utils: xorg-x11-server-utils
pkg_xorg_server: xorg-x11-server-Xorg
pkg_xorg_video: xorg-x11-drv
php_ini_path: /etc/php.ini
polkitd_user: polkitd
qemu_guest_agent_service: qemu-guest-agent
svc_apache2: httpd
svc_display_mgr: gdm
svc_mysql: mariadb
user_apache: httpd
user_spamd: spamd
user_spamass_milter: sa-milt
