- name: Common system setup
  hosts: all
  user: "{{ user }}"
  become: yes
  become_method: sudo

  pre_tasks:
    - name: create OS group
      group_by:
        key: "os_{{ ansible_distribution }}_{{ (ansible_os_family == 'RedHat')|ternary(ansible_distribution_major_version, ansible_distribution_version)|replace('.','_') }}"
      changed_when: False
      tags:
        - always

  tasks:
    - name: copy dump to host
      copy:
        src: sqldump/nextcloud.sql.xz
        dest: /root/nextcloud.sql.xz

    - name: import nextcloud mysql database
      mysql_db:
        name: nextcloud
        state: present
        login_user: root
        login_password: "{{ mysql_password }}"
        state: import
        target: /root/nextcloud.sql.xz
      vars:
        ansible_python_interpreter: python3
