---
# file: site.yml
#
# This is the master playbook. It includes all other playbooks.

- name: Common system setup
  hosts: all
  user: "{{ user }}"
  become: yes
  become_method: sudo

  pre_tasks:
    - name: create OS group
      group_by:
        key: "os_{{ ansible_distribution }}_{{ (ansible_os_family == 'RedHat')|ternary(ansible_distribution_major_version, ansible_distribution_version)|replace('.','_') }}"
      changed_when: False
      tags:
        - always

  roles:
   - common
   - console

- name: Server setup
  hosts: servers
  user: "{{ user }}"
  become: yes
  become_method: sudo

  roles:
   - server
   - apache-base
   - letsencrypt-cert
   - apache-vhost
   - mysql
   - nextcloud
   - email-server
   #- firefox-sync-server

- name: setup desktop system
  hosts: desktops
  user: "{{ user }}"
  become: yes
  become_method: sudo

  roles:
    - desktop
    - i3wm
    - devel
    - latex
