---
# file: roles/desktop/tasks/gnome.yml
- name: Ensure GNOME environment is installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ pkg_gnome }}"
    - python-psutil
  tags:
    - dconf
    - packages

- name: Enable gdm.service at startup
  service: name={{ svc_display_mgr }} state=started
  tags:
    - services

- name: "gtk-3.0 config directory"
  file:
    dest: "{{ homedir }}/.config/gtk-3.0"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0700
  become: no
  tags:
    - homedir

- name: "gtk-3.0 CSS override"
  copy:
    src: gtk.css
    dest: "{{ homedir }}/.config/gtk-3.0"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  become: no
  tags:
    - homedir

- name: "Disable menubar for GNOME terminal"
  dconf:
    key: "/org/gnome/terminal/legacy/default-show-menubar"
    value: "false"
    state: present
  become: no
  tags:
    - configuration
    - dconf
