---
# file: roles/desktop/tasks/laptop.yml
- name: Install laptop-related packages
  package: name={{ item }} state=present
  with_items:
    - powertop
    - "{{ pkg_xorg_input }}-synaptics"
  tags:
    - packages
