---
# file: roles/desktop/tasks/laptop.yml
- name: Install laptop-related packages
  package:
    state: present
    name:
      - powertop
      - "{{ pkg_xorg_input }}-synaptics"
  tags:
    - packages
