---
# file: roles/desktop/tasks/main.yml
- name: Install desktop packages
  package: name={{ item }} state=present
  with_items:
    - baobab
    - brasero
    - cheese
    - deja-dup
    - dia
    - firefox
    - gitg
    - gnucash
    - inkscape
    - "{{ pkg_keepass2 }}"
    - ktouch
    - libreoffice-calc
    - libreoffice-impress
    - libreoffice-writer
    - liferea
    - nautilus
    - "{{ pkg_network_manager_openvpn }}"
    - "{{ pkg_okteta }}"
    - "{{ pkg_rxvt_unicode }}"
    - xdotool
    - seahorse
    - thunderbird
    - "{{ pkg_lightning_gdata }}"
    - vinagre
    - "{{ pkg_wireshark }}"
    - "{{ pkg_xorg_font_utils }}"
    - "{{ pkg_xorg_server_utils }}"
    - "{{ pkg_xorg_server }}"
  tags:
    - packages

- include_tasks: laptop.yml
  when: laptop
- include_tasks: graphics-intel.yml
  when: graphics_vendor == "intel"
- include_tasks: graphics-nouveau.yml
  when: graphics_vendor == "nouveau"
- import_tasks: gnome.yml
- import_tasks: apps.yml
- import_tasks: polkit.yml

- name: Enable ufw
  service:
    name: ufw
    state: started
    enabled: yes
  when: firewall_package == 'ufw'
  tags:
    - firewall
    - services
