---
# roles/webdev/tasks/rails.yml
- name: Install Ruby on Rails development packages
  package:
    state: present
    name:
      - ruby
      - "ruby-{{ dev }}"
      - rubygems
      - "{{ pkg_ruby_rails }}"
      - "{{ pkg_rake }}"
  tags:
    - packages
