---
- name: Create LetsEncrypt account private key
  openssl_privatekey:
    curve: secp384r1
    force: false
    format: auto_ignore
    owner: root
    group: root
    mode: '600'
    path: /etc/ssl/private/account.key
    size: 4096
    state: present
    type: RSA
  tags:
    - certificates

- name: Create LetsEncypt account
  acme_account:
    account_key_src: /etc/ssl/private/account.key
    contact:
      - "mailto:{{ user }}@{{ mail_domain }}"
    acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
    acme_version: 2
    allow_creation: yes
    state: present
    terms_agreed: yes
  register: letsencrypt_account
  tags:
    - certificates

- name: Create LetsEncrypt certificate private key
  openssl_privatekey:
    curve: secp384r1
    force: false
    format: auto_ignore
    owner: root
    group: root
    mode: '600'
    path: /etc/ssl/private/{{ www_fqdn }}.key
    size: 4096
    state: present
    type: RSA
  tags:
    - certificates

- name: Create LetsEncrypt CSR
  openssl_csr:
    common_name: "{{ www_fqdn }}"
    digest: sha256
    owner: root
    group: root
    mode: '600'
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    path: "/etc/ssl/{{ www_fqdn }}.csr"
    privatekey_path: "/etc/ssl/private/{{ www_fqdn }}.key"
    state: present
    subject_alt_name: "{{www_aliases|map('regex_replace','^(.+)$', 'DNS:\\1') }}"
  register: letsencrypt_csr
  tags:
    - certificates

- name: Request LetsEncrypt challenge
  acme_certificate:
    account_key_src: /etc/ssl/private/account.key
    account_uri: "{{ letsencrypt_account.account_uri }}"
    acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
    acme_version: 2
    csr: /etc/ssl/{{ www_fqdn }}.csr
    dest: /etc/ssl/{{ www_fqdn }}.crt
    chain_dest: /etc/ssl/{{ www_fqdn }}.chain.pem
    fullchain_dest: /etc/ssl/{{ www_fqdn }}.fullchain.pem
    modify_account: no
    challenge: http-01
    remaining_days: 20
    terms_agreed: yes
  register: www_ssl_challenge
  tags:
    - certificates

- name: Create well-known ACME challenge directory
  file:
    path: /var/www/html/.well-known/acme-challenge
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - certificates

- block:
    - name: Fulfill LetsEncrypt challenges
      copy:
        dest: /var/www/html/{{ item.value['http-01']['resource'] }}
        content: "{{ item.value['http-01']['resource_value'] }}"
      with_dict: "{{ www_ssl_challenge['challenge_data'] }}"
      when: www_ssl_challenge is changed
      tags:
        - certificates

    - name: Request LetsEncrypt certificate
      acme_certificate:
        account_key: /etc/ssl/private/account.key
        account_email: "{{ user }}@{{ mail_domain }}"
        acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
        csr: /etc/ssl/{{ www_fqdn }}.csr
        dest: /etc/ssl/{{ www_fqdn }}.crt
        chain_dest: /etc/ssl/{{ www_fqdn }}.chain.pem
        fullchain_dest: /etc/ssl/{{ www_fqdn }}.fullchain.pem
        data: "{{ www_ssl_challenge }}"
        remaining_days: 20
        challenge: http-01
        acme_version: 2
        terms_agreed: yes
      notify: Install fullchain PEM
      tags:
        - certificates

    - name: Install intermediate chain
      copy:
        src: lets-encrypt-r3.pem
        dest: /etc/ssl/{{ www_fqdn }}.chain.pem
        owner: root
        group: root
        mode: 0644
      tags:
        - certificates

  always:
    - name: Remove challenge files
      file:
        path: "{{ item.value['http-01']['resource'] }}"
        state: absent
      with_dict: "{{ www_ssl_challenge['challenge_data'] }}"
      when: www_ssl_challenge is changed
      tags:
        - certificates

    - name: Force generation of fullchain PEM
      meta: flush_handlers
