---
- name: Create LetsEncrypt account private key
  command: openssl genrsa -out /etc/ssl/private/account.key 2048
  args:
      creates: /etc/ssl/private/account.key
  tags:
    - certificates

- name: Install openssl configuration for CSR generation
  template:
    src: openssl.cnf.j2
    dest: /etc/ssl/{{ www_fqdn }}.cnf
    owner: root
    group: root
    mode: 0644
  tags:
    - certificates

- name: Create LetsEncrypt certificate private key
  command: openssl genrsa -out /etc/ssl/private/{{ www_fqdn }}.key 2048
  args:
      creates: /etc/ssl/private/{{ www_fqdn }}.key
  tags:
    - certificates

- name: Create LetsEncrypt CSR
  command: "openssl req -new -sha256 -batch -subj /CN={{ www_fqdn }}/ -key /etc/ssl/private/{{ www_fqdn }}.key -out /etc/ssl/{{ www_fqdn }}.csr -config /etc/ssl/{{ www_fqdn }}.cnf"
  args:
      creates: /etc/ssl/{{ www_fqdn }}.csr
  tags:
    - certificates

- name: Request LetsEncrypt challenge
  letsencrypt:
    account_key: /etc/ssl/private/account.key
    account_email: "{{ user }}@{{ mail_domain }}"
    acme_directory: "https://acme-v01.api.letsencrypt.org/directory"
    agreement: "https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf"
    csr: /etc/ssl/{{ www_fqdn }}.csr
    dest: /etc/ssl/{{ www_fqdn }}.crt
    challenge: http-01
  register: www_ssl_challenge
  tags:
    - certificates

- name: Create well-known ACME challenge directory
  file:
    path: /var/www/html/.well-known/acme-challenge
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - certificates

- block:
    - name: Fulfill LetsEncrypt challenges
      copy:
        dest: /var/www/html/{{ item.value['http-01']['resource'] }}
        content: "{{ item.value['http-01']['resource_value'] }}"
      with_dict: "{{ www_ssl_challenge['challenge_data'] }}"
      when: www_ssl_challenge|changed
      tags:
        - certificates

    - name: Request LetsEncrypt certificate
      letsencrypt:
        account_key: /etc/ssl/private/account.key
        account_email: "{{ user }}@{{ mail_domain }}"
        acme_directory: "https://acme-v01.api.letsencrypt.org/directory"
        agreement: "https://letsencrypt.org/documents/LESA-v1.1.1-August-1-2016.pdf"
        csr: /etc/ssl/{{ www_fqdn }}.csr
        dest: /etc/ssl/{{ www_fqdn }}.crt
        data: "{{ www_ssl_challenge }}"
        challenge: http-01
      notify: Install fullchain PEM
      tags:
        - certificates

    - name: Install intermediate chain
      copy:
        src: lets-encrypt-x3-cross-signed.pem
        dest: /etc/ssl/{{ www_fqdn }}.chain.pem
        owner: root
        group: root
        mode: 0644
      tags:
        - certificates

  always:
    - name: Remove challenge files
      file:
        path: "{{ item.value['http-01']['resource'] }}"
        state: absent
      with_dict: "{{ www_ssl_challenge['challenge_data'] }}"
      when: www_ssl_challenge|changed
      tags:
        - certificates

    - name: Force generation of fullchain PEM
      meta: flush_handlers
