---
# file: roles/apache/handlers/main.yml

- name: restart apache web server
  service: name={{ svc_apache2 }} state=restarted

- name: reload apache web server
  service: name={{ svc_apache2 }} state=reloaded
