---
# file: roles/nextcloud/tasks/main.yml

- name: ensure dependencies are installed
  package:
    state: present
    name:
      - "php{{ php_ver }}-curl"
      - "php{{ php_ver }}-bcmath"
      - "php{{ php_ver }}-gd"
      - "php{{ php_ver }}-gmp"
      - "php{{ php_ver }}-intl"
      - php-imagick
      - php-json
      - "php{{ php_ver }}-mbstring"
      - "{{ pkg_php_mysql }}"
      - "{{ pkg_php_pdo }}"
      - "php{{ php_ver }}-xml"
      - "php{{ php_ver }}-zip"
  notify: restart apache web server
  tags:
    - packages
    - nextcloud

- name: Test for nextcloud installation
  stat: "path={{ nextcloud_dir }}/public.php"
  register: nextcloud_public_php
  tags:
    - configuration
    - nextcloud

- name: download nextcloud
  get_url:
    dest: /var/www/nextcloud.zip
    url: https://download.nextcloud.com/server/releases/nextcloud-25.0.8.zip
    checksum: sha256:https://download.nextcloud.com/server/releases/nextcloud-25.0.8.zip.sha256
  when: not nextcloud_public_php.stat.exists
  tags:
    - apache
    - nextcloud

- name: untar nextcloud
  unarchive:
    src: /var/www/nextcloud.zip
    dest: /var/www
    remote_src: true
    owner: "{{ user_apache }}"
    group: "{{ user_apache }}"
    mode: u=rwX,g=rX
    creates: /var/www/nextcloud/public.php
  tags:
    - apache
    - nextcloud

- name: ensure apache web server can connect to MySQL
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes
  when: "'redhat' in ansible_os_family|lower"
  tags:
    - configuration
    - apache
    - nextcloud
    - database

- name: create nextcloud mysql database
  mysql_db:
    name: "{{ nextcloud_database }}"
    state: present
    login_user: root
    login_password: "{{ mysql_password }}"
    collation: utf8mb4_general_ci
    encoding: utf8mb4
  tags:
    - configuration
    - nextcloud
    - database

- name: create nextcloud mysql user
  mysql_user:
    name: "{{ nextcloud_database_user }}"
    password: "{{ nextcloud_database_password }}"
    priv: "{{ nextcloud_database }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_password }}"
  tags:
    - configuration
    - nextcloud
    - database

- name: set up nextcloud configuration file
  template:
    src: config.php.j2
    dest: "{{ nextcloud_config_dir }}/config.php"
    owner: "{{ user_apache }}"
    group: "{{ user_apache }}"
    mode: 0660
    setype: httpd_sys_rw_content_t
  tags:
    - configuration
    - nextcloud

- name: enable apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - mpm_prefork
    - dir
    - env
    - headers
    - mime
    - rewrite
  when: "'debian' in ansible_os_family|lower"
  notify: reload apache web server
  tags:
    - apache
    - nextcloud

- name: enable PHP for apache
  apache2_module:
    name: "{{ php_ver }}"
    identifier: "php_module"
    state: present
  notify: reload apache web server
  tags:
    - apache
    - nextcloud

- name: set up nextcloud apache configuration file
  copy:
    src: apache-nextcloud.conf
    dest: "{{ dir_apache2_conf }}/conf-available/nextcloud.conf"
    owner: root
    group: root
    mode: 0644
  tags:
    - apache
    - configuration
    - nextcloud

- block:
    - name: Enable apache nextcloud config
      file:
        src: "{{ dir_apache2_conf }}/conf-available/nextcloud.conf"
        dest: "{{ dir_apache2_conf }}/conf-enabled/nextcloud.conf"
        state: link
      notify: reload apache web server
      tags:
        - apache
        - configuration
        - nextcloud

    - name: Verify apache configuration
      command: apache2ctl configtest
      changed_when: False
      check_mode: no
      tags:
        - apache
        - configuration
        - nextcloud

  rescue:
    - name: Disable apache default vhost
      file:
        dest: "{{ dir_apache2_conf }}/conf-enabled/nextcloud.conf"
        state: absent
      tags:
        - apache
        - configuration
        - nextcloud

    - name: Fail
      fail:
        msg: Apache config test failed
      tags:
        - apache
        - configuration
        - nextcloud
