# .bash_profile

# Red Hat does this in ~/.bash_profile, I am going to trust them and do path
# changes here
if [ -d "$HOME/bin" ] && [[ ":$PATH:" !=  *":$!:"* ]]; then
	PATH=$PATH:$HOME/bin
	export PATH
fi


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
[[ -f ~/.bashrc ]] && . ~/.bashrc

# Show X11 display
if [ -n "$DISPLAY" ]; then
	echo X11 display is $DISPLAY
fi

# Make sure that our terminal is supported
SCREEN_COLORS=$(tput colors 2>/dev/null)
if [ -z "$SCREEN_COLORS" ] ; then
        TERMOLD=$TERM
        TERM=${TERM%-*}
        SCREEN_COLORS=$(tput colors 2>/dev/null)
        while [[ "$TERM" == "*-*" && -z "$SCREEN_COLORS" ]]; do
                TERM=${TERM%-*}
        done

        if [[ -n "$SCREEN_COLORS" ]]; then
                echo "Unknown terminal $TERMOLD. Falling back to '$TERM'."
        fi
        unset TERMOLD
fi

# Show terminal type and setup terminal
echo "Terminal type is $TERM."
tset

if [[ "$TERMBG" == "dark" || "$TERMBG" == "light" || "$TERMBG" == "solarized" ]]
then
	echo "Terminal background is $TERMBG."
else
	echo "Please set TERMBG=light or TERMBG=dark and run recolor."
fi
export TERMBG

# Let us know if we've got running screen sessions
if [[ -n $(type -t screen) ]]; then
	screen -ls
fi

# Display something witty :)
if [[ -n $(type -t fortune) ]]; then
	fortune
fi

if [[ -f ~/.bash_profile.local ]]; then
	. ~/.bash_profile.local
fi
