---
session_name: default
start_directory: ~/
windows:
  - window_name: tasksh
    focus: true
    panes:
      - shell_command:
          - exec tasksh
  - window_name: sdjournal
    panes:
      - shell_command:
          - exec sudo journalctl --follow
  - window_name: dis
    start_directory: ~/doc/papers/dissertation
    panes:
      - focus: true
