---
# file: roles/common/tasks/user.yml
- name: Create system groups
  group:
    name: "{{ item }}"
    system: yes
  loop: "{{ user_system_groups }}"
  tags:
    - configuration

- name: Create user-private group
  group:
    name: "{{ user }}"
    system: no
  tags:
    - configuration

- name: Create user account
  user:
    name: "{{ user }}"
    comment: "{{ fullname }}"
    home: "{{ homedir }}"
    createhome: no
    group: "{{ user }}"
    groups: "{{ user_system_groups }}"
    password: "{{ user_password }}"
  tags:
    - configuration

- import_tasks: home.yml
