#!/usr/bin/env zsh
# Converts a TLA+ source file to LaTeX
# Patrick MacArthur <contact@patrickmacarthur.net>

java -cp "$TLAHOME" -showversion tla2tex.TLA -shade \
     -textwidth 550 -textheight 725 -hoffset -100 -voffset -100 "$@"
