---
# file: roles/console/handlers/main.yml

- name: Run localectl
  command: localectl set-keymap us-dvorak
  notify: Regenerate initramfs

- name: Regenerate initramfs
  command: "{{ cmd_update_initramfs }}"

- name: Restart SSH
  service:
    name: "{{ svc_sshd }}"
    state: restarted
