---
# file: roles/console/tasks/bash.yml
- name: Install Bourne Again Shell startup files
  copy:
    dest: "{{ homedir }}/.{{ item }}"
    src: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  with_items:
    - bashrc
    - bash_profile
    - bash_logout
    - inputrc
  tags:
    - homedir
