---
# file: roles/console/tasks/dvorak.yml
- name: Install console-data
  package:
      name: console-data
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('22.04', '>=')
  tags:
    - packages

- name: Set keyboard layout in vconsole.conf
  lineinfile:
      dest: /etc/vconsole.conf
      regexp: "^KEYMAP="
      line: "KEYMAP=us-dvorak"
      create: yes
  notify: Run localectl
  tags:
    - configuration
