---
# file: roles/console/tasks/git.yml
- name: Install git configuration file
  template:
    dest: "{{ homedir }}/.gitconfig"
    src: "gitconfig.j2"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  tags:
    - homedir

- name: Install git ignore filters
  copy:
    dest: "{{ homedir }}/.cvsignore"
    src: "cvsignore"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  tags:
    - homedir

- name: Create git template parent directories
  file:
    dest: "{{ homedir }}/.local/share/git-core"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  tags:
    - homedir

- name: Install git template directory
  copy:
    dest: "{{ homedir }}/.local/share/git-core"
    src: templates
    owner: "{{ user }}"
    group: "{{ group }}"
  tags:
    - homedir

- name: Create branches subdirectory in git template
  file:
    dest: "{{ homedir }}/.local/share/git-core/templates/branches"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  tags:
    - homedir
