---
# file: roles/console/tasks/git.yml
- name: Install git configuration file
  template:
    dest: "{{ homedir }}/.gitconfig"
    src: "gitconfig.j2"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  tags:
    - homedir
