---
# file: roles/console/tasks/main.yml
- import_tasks: dvorak.yml
- import_tasks: ssh.yml
- import_tasks: tmux.yml
- import_tasks: git.yml
- import_tasks: vim.yml
- import_tasks: sh.yml

- name: Copy dircolors in place
  copy:
    src: dircolors.ansi-universal
    dest: "{{ homedir }}/.dircolors"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  tags:
    - homedir
