---
# file: roles/console/tasks/sh.yml
- name: Install bash completion directory
  file:
    dest: "{{ homedir }}/.local/share/bash-completion"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  become: no
  tags:
    - homedir
