---
# file: roles/console/tasks/ssh.yml
- name: Disable root SSH
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^#?PermitRootLogin"
    line: PermitRootLogin without-password
  notify: Restart SSH
  tags:
    - configuration

- name: Install OpenSSH client configuration
  template:
    dest: "{{ homedir }}/.ssh/config"
    src: "ssh_config.j2"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0600
    setype: ssh_home_t
  tags:
    - homedir

- name: Add github public SSH host key
  lineinfile:
    dest: /etc/ssh/ssh_known_hosts
    state: present
    create: yes
    line: "github.com,204.232.175.90 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
