---
# file: roles/console/tasks/ssh.yml
- name: Disable root SSH
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^#?PermitRootLogin"
    line: PermitRootLogin without-password
  notify: Restart SSH
  tags:
    - configuration
