---
# file: roles/console/tasks/tmux.yml
- name: Check for existence of tmux terminal type
  command: /usr/bin/infocmp tmux-256color
  changed_when: False
  ignore_errors: True
  register: term_tmux
  tags:
    - tmux
    - configuration

- block:
    - name: Install extra ncurses terminal definitions
      package:
        name: ncurses-term
        state: present
      tags:
        - packages
        - tmux

    - name: Create temp file
      command: mktemp
      register: terminfo_source
      tags:
        - configuration
        - tmux

    - name: Copy tmux terminal type source
      copy:
        src: tmux.terminfo
        dest: "{{ terminfo_source|stdout }}"
      tags:
        - configuration
        - tmux

    - name: Install tmux terminal types
      command: /usr/bin/tic "{{ terminfo_source|stdout }}"
      tags:
        - configuration
        - tmux

  always:
    - name: Remove temp file
      file:
        name: "{{ terminfo_source|stdout }}"
        state: absent
      when: terminfo_source is defined
      tags:
        - configuration
        - tmux

  when: term_tmux is failed

- name: Install tmuxp
  package:
    name: "{{ pkg_tmuxp|default('') }}"
    state: present
  when: pkg_tmuxp is defined
  tags:
    - packages
    - tmux
