---
# file: roles/console/tasks/vim.yml
- name: Install other vim support files
  copy:
    dest: "{{ homedir }}"
    src: ".vim"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  tags:
    - homedir

- name: Create bundle directory
  file:
    path: "{{ homedir }}/.vim/bundle"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  tags:
    - homedir

- name: Install pathogen and other tpope bundles
  become: no
  remote_user: "{{ user }}"
  git:
    repo: https://github.com/tpope/{{ item }}.git
    dest: "{{ homedir }}/.vim/bundle/{{ item }}"
    version: master
  with_items:
    - vim-pathogen
    - vim-fugitive
    - vim-sensible
  tags:
    - homedir

- name: Install tabular plugin for vim
  become: no
  remote_user: "{{ user }}"
  git:
    repo: https://github.com/godlygeek/tabular.git
    dest: "{{ homedir }}/.vim/bundle/tabular"
    version: master
  tags:
    - homedir

- name: Install ansible-vim-yaml plugin for vim
  become: no
  remote_user: "{{ user }}"
  git:
    repo: https://github.com/pearofducks/ansible-vim.git
    dest: "{{ homedir }}/.vim/bundle/ansible-vim"
    version: master
  tags:
    - homedir

- name: Install solarized color scheme for vim
  become: no
  remote_user: "{{ user }}"
  git:
    repo: git://github.com/patrickmacarthur/vim-colors-solarized.git
    dest: "{{ homedir }}/.vim/bundle/vim-colors-solarized"
    remote: origin
    version: master
  tags:
    - homedir

- name: Install vimrc
  copy:
    dest: "{{ homedir }}/.vimrc"
    src: "vimrc"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  tags:
    - homedir
